### ISSUE TITLE
Broken link to repository

### ISSUE THREAD

**Issue by willu47** [RSEToolkit/RSEToolkit.github.io#2]
**Error type**
What type of error are you reporting? _(replace [ ] with [x] to check the relevant box in the list below)_

- [ ] **Presentation error:** A typo, grammatical error or an error in the way content is rendered or displayed
- [X] **Content error:** An error in the content itself - content that is incorrect or lacking significant detail
- [ ] **Other error:** Another type of error with the content not represented by the above options

**Where is the error?**
Please provide the location within the RSE Toolkit content of the error(s) you are reporting.

Link in https://github.com/RSEToolkit/RSEToolkit.github.io/blob/main/docs/index.md points to jcoen2 github repository rather than new one.

_Where possible, please include a [permalink](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/getting-permanent-links-to-files) to the location of the error. If you are reporting multiple errors, you can list the locations here or provide details within the description below._

**Error description**
Please provide a clear and concise description of the error.

**Suggested fix**
If you have a suggestion for how to fix the error, please include it here.

replace with link to https://github.com/RSEToolkit/RSEToolkit.github.io

**Additional context**
If you wish to provide any additional information in relation to this error, please add it here.

_Thank you very much for your contribution to ensuring that the content of the RSE Toolkit is valid and up-to-date. We very much appreciate your input without which the resource cannot be sustained._

**Comment by jcohen02** [comment]
Many thanks for spotting this and opening the issue @willu47. Fixed in bedbb18.
