### ISSUE TITLE
add articles on RSE group structures?

### ISSUE THREAD

**Issue by danielskatz** [RSEToolkit/RSEToolkit.github.io#31]
You could potentially add some articles on how RSE groups are structured, such as 
* https://doi.org/10.1109/SE4Science.2019.00009 (preprint http://arxiv.org/abs/1903.00732)
* https://doi.iorg/10.1109/MCSE.2023.3264113 (preprint https://arxiv.org/abs/2210.16261)

There are likely other such papers, though I can't find any right now...

**Comment by jcohen02** [comment]
Many thanks @danielskatz, apologies for the delay, this is now added in #32.
